apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: churnai-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - churnai.example.com
      secretName: churnai-tls
  rules:
    - host: churnai.example.com
      http:
        paths:
          - path: /v1
            pathType: Prefix
            backend:
              service:
                name: churnai-backend-svc
                port:
                  number: 8000
          - path: /
            pathType: Prefix
            backend:
              service:
                name: churnai-frontend-svc
                port:
                  number: 3000
